export interface RealFootballTeam {
  id: string;
  name: string;
  shortName: string;
  short?: string;
  division: "Division 1" | "Division 2" | "Division 3";
  league: "Premier League" | "La Liga" | "Ligue 1";
  country: string;
  logo: string;
  primaryColor: string;
  secondaryColor: string;
}

// 20 Premier League Teams for Division 1
export const PREMIER_LEAGUE_TEAMS: RealFootballTeam[] = [
  {
    id: "arsenal",
    name: "Arsenal FC",
    shortName: "ARS",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/57.svg",
    primaryColor: "#EF0107",
    secondaryColor: "#063672",
  },
  {
    id: "aston-villa",
    name: "Aston Villa FC",
    shortName: "AVL",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/58.svg",
    primaryColor: "#95BFE5",
    secondaryColor: "#670E36",
  },
  {
    id: "bournemouth",
    name: "AFC Bournemouth",
    shortName: "BOU",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/1044.svg",
    primaryColor: "#DA291C",
    secondaryColor: "#000000",
  },
  {
    id: "brentford",
    name: "Brentford FC",
    shortName: "BRE",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/402.svg",
    primaryColor: "#E30613",
    secondaryColor: "#FBB800",
  },
  {
    id: "brighton",
    name: "Brighton & Hove Albion",
    shortName: "BHA",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/397.svg",
    primaryColor: "#0057B8",
    secondaryColor: "#FFCD00",
  },
  {
    id: "chelsea",
    name: "Chelsea FC",
    shortName: "CHE",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/61.svg",
    primaryColor: "#034694",
    secondaryColor: "#EE242C",
  },
  {
    id: "crystal-palace",
    name: "Crystal Palace FC",
    shortName: "CRY",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/354.svg",
    primaryColor: "#1B458F",
    secondaryColor: "#C4122E",
  },
  {
    id: "everton",
    name: "Everton FC",
    shortName: "EVE",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/62.svg",
    primaryColor: "#003399",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "fulham",
    name: "Fulham FC",
    shortName: "FUL",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/63.svg",
    primaryColor: "#000000",
    secondaryColor: "#CC0000",
  },
  {
    id: "ipswich-town",
    name: "Ipswich Town FC",
    shortName: "IPS",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/349.svg",
    primaryColor: "#0047AB",
    secondaryColor: "#ED1C24",
  },
  {
    id: "leicester-city",
    name: "Leicester City FC",
    shortName: "LEI",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/338.svg",
    primaryColor: "#003090",
    secondaryColor: "#FDBE11",
  },
  {
    id: "liverpool",
    name: "Liverpool FC",
    shortName: "LIV",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/64.svg",
    primaryColor: "#C8102E",
    secondaryColor: "#00B2A9",
  },
  {
    id: "manchester-city",
    name: "Manchester City",
    shortName: "MCI",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/65.svg",
    primaryColor: "#6CABDD",
    secondaryColor: "#1C2C5B",
  },
  {
    id: "manchester-united",
    name: "Manchester United",
    shortName: "MUN",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/66.svg",
    primaryColor: "#DA291C",
    secondaryColor: "#FBE122",
  },
  {
    id: "newcastle-united",
    name: "Newcastle United",
    shortName: "NEW",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/67.svg",
    primaryColor: "#241F20",
    secondaryColor: "#41B6E6",
  },
  {
    id: "nottingham-forest",
    name: "Nottingham Forest",
    shortName: "NFO",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/351.svg",
    primaryColor: "#DD0000",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "southampton",
    name: "Southampton FC",
    shortName: "SOU",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/340.svg",
    primaryColor: "#D71920",
    secondaryColor: "#130F54",
  },
  {
    id: "tottenham-hotspur",
    name: "Tottenham Hotspur",
    shortName: "TOT",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/73.svg",
    primaryColor: "#132257",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "west-ham-united",
    name: "West Ham United",
    shortName: "WHU",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/563.svg",
    primaryColor: "#7A263A",
    secondaryColor: "#1BB1E7",
  },
  {
    id: "wolverhampton",
    name: "Wolverhampton Wanderers",
    shortName: "WOL",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/76.svg",
    primaryColor: "#FDB913",
    secondaryColor: "#231F20",
  },
];

// 20 La Liga Teams for Division 2
export const LA_LIGA_TEAMS: RealFootballTeam[] = [
  {
    id: "real-madrid",
    name: "Real Madrid CF",
    shortName: "RMA",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/86.svg",
    primaryColor: "#FEBE10",
    secondaryColor: "#00529F",
  },
  {
    id: "fc-barcelona",
    name: "FC Barcelona",
    shortName: "BAR",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/81.svg",
    primaryColor: "#004D98",
    secondaryColor: "#A50044",
  },
  {
    id: "atletico-madrid",
    name: "Atlético de Madrid",
    shortName: "ATM",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/78.svg",
    primaryColor: "#CB3524",
    secondaryColor: "#272E61",
  },
  {
    id: "athletic-bilbao",
    name: "Athletic Club Bilbao",
    shortName: "ATH",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/77.svg",
    primaryColor: "#EE2524",
    secondaryColor: "#000000",
  },
  {
    id: "girona",
    name: "Girona FC",
    shortName: "GIR",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/298.svg",
    primaryColor: "#CD1318",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "real-sociedad",
    name: "Real Sociedad",
    shortName: "RSO",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/92.svg",
    primaryColor: "#0067B1",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "real-betis",
    name: "Real Betis",
    shortName: "BET",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/90.svg",
    primaryColor: "#0BB364",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "villarreal",
    name: "Villarreal CF",
    shortName: "VIL",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/94.svg",
    primaryColor: "#FFE667",
    secondaryColor: "#005187",
  },
  {
    id: "valencia",
    name: "Valencia CF",
    shortName: "VAL",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/95.svg",
    primaryColor: "#FF7300",
    secondaryColor: "#000000",
  },
  {
    id: "sevilla",
    name: "Sevilla FC",
    shortName: "SEV",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/559.svg",
    primaryColor: "#D4001F",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "osasuna",
    name: "CA Osasuna",
    shortName: "OSA",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/79.svg",
    primaryColor: "#D91A21",
    secondaryColor: "#001E62",
  },
  {
    id: "getafe",
    name: "Getafe CF",
    shortName: "GET",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/82.svg",
    primaryColor: "#005999",
    secondaryColor: "#D00C27",
  },
  {
    id: "celta-vigo",
    name: "RC Celta de Vigo",
    shortName: "CEL",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/558.svg",
    primaryColor: "#87CEEB",
    secondaryColor: "#C4122E",
  },
  {
    id: "mallorca",
    name: "RCD Mallorca",
    shortName: "MLL",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/89.svg",
    primaryColor: "#E20613",
    secondaryColor: "#000000",
  },
  {
    id: "las-palmas",
    name: "UD Las Palmas",
    shortName: "LPA",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/275.svg",
    primaryColor: "#FFD700",
    secondaryColor: "#005BAC",
  },
  {
    id: "rayo-vallecano",
    name: "Rayo Vallecano",
    shortName: "RAY",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/87.svg",
    primaryColor: "#E30613",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "espanyol",
    name: "RCD Espanyol",
    shortName: "ESP",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/80.svg",
    primaryColor: "#007FC8",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "leganes",
    name: "CD Leganés",
    shortName: "LEG",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/745.svg",
    primaryColor: "#0055A5",
    secondaryColor: "#009540",
  },
  {
    id: "real-valladolid",
    name: "Real Valladolid",
    shortName: "VLD",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/250.svg",
    primaryColor: "#5B2C6F",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "deportivo-alaves",
    name: "Deportivo Alavés",
    shortName: "ALA",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/263.svg",
    primaryColor: "#005CA9",
    secondaryColor: "#FFFFFF",
  },
];

// 20 Ligue 1 Teams for Division 3
export const LIGUE_1_TEAMS: RealFootballTeam[] = [
  {
    id: "psg",
    name: "Paris Saint-Germain",
    shortName: "PSG",
    division: "Division 3",
    league: "Ligue 1",
    country: "France",
    logo: "https://crests.football-data.org/524.svg",
    primaryColor: "#004170",
    secondaryColor: "#DA291C",
  },
  {
    id: "as-monaco",
    name: "AS Monaco",
    shortName: "ASM",
    division: "Division 3",
    league: "Ligue 1",
    country: "France",
    logo: "https://crests.football-data.org/548.svg",
    primaryColor: "#E2001A",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "stade-brestois",
    name: "Stade Brestois 29",
    shortName: "SB29",
    division: "Division 3",
    league: "Ligue 1",
    country: "France",
    logo: "https://crests.football-data.org/512.svg",
    primaryColor: "#E2001A",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "losc-lille",
    name: "LOSC Lille",
    shortName: "LOSC",
    division: "Division 3",
    league: "Ligue 1",
    country: "France",
    logo: "https://crests.football-data.org/521.svg",
    primaryColor: "#E01E2E",
    secondaryColor: "#1A2742",
  },
  {
    id: "ogc-nice",
    name: "OGC Nice",
    shortName: "OGCN",
    division: "Division 3",
    league: "Ligue 1",
    country: "France",
    logo: "https://crests.football-data.org/522.svg",
    primaryColor: "#ED1C24",
    secondaryColor: "#000000",
  },
  {
    id: "olympique-lyonnais",
    name: "Olympique Lyonnais",
    shortName: "OL",
    division: "Division 3",
    league: "Ligue 1",
    country: "France",
    logo: "https://crests.football-data.org/523.svg",
    primaryColor: "#002F6C",
    secondaryColor: "#DA291C",
  },
  {
    id: "rc-lens",
    name: "RC Lens",
    shortName: "RCL",
    division: "Division 3",
    league: "Ligue 1",
    country: "France",
    logo: "https://crests.football-data.org/546.svg",
    primaryColor: "#ED1C24",
    secondaryColor: "#FFE600",
  },
  {
    id: "marseille",
    name: "Olympique de Marseille",
    shortName: "OM",
    division: "Division 3",
    league: "Ligue 1",
    country: "France",
    logo: "https://crests.football-data.org/516.svg",
    primaryColor: "#00A3E0",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "stade-de-reims",
    name: "Stade de Reims",
    shortName: "SDR",
    division: "Division 3",
    league: "Ligue 1",
    country: "France",
    logo: "https://crests.football-data.org/547.svg",
    primaryColor: "#E2001A",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "stade-rennais",
    name: "Stade Rennais FC",
    shortName: "SRFC",
    division: "Division 3",
    league: "Ligue 1",
    country: "France",
    logo: "https://crests.football-data.org/529.svg",
    primaryColor: "#E30613",
    secondaryColor: "#000000",
  },
  {
    id: "toulouse-fc",
    name: "Toulouse FC",
    shortName: "TFC",
    division: "Division 3",
    league: "Ligue 1",
    country: "France",
    logo: "https://crests.football-data.org/511.svg",
    primaryColor: "#6B3B8B",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "montpellier",
    name: "Montpellier HSC",
    shortName: "MHSC",
    division: "Division 3",
    league: "Ligue 1",
    country: "France",
    logo: "https://crests.football-data.org/518.svg",
    primaryColor: "#002B49",
    secondaryColor: "#F37021",
  },
  {
    id: "strasbourg",
    name: "RC Strasbourg Alsace",
    shortName: "RCSA",
    division: "Division 3",
    league: "Ligue 1",
    country: "France",
    logo: "https://crests.football-data.org/576.svg",
    primaryColor: "#0055A5",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "fc-nantes",
    name: "FC Nantes",
    shortName: "FCN",
    division: "Division 3",
    league: "Ligue 1",
    country: "France",
    logo: "https://crests.football-data.org/543.svg",
    primaryColor: "#008559",
    secondaryColor: "#FFF200",
  },
  {
    id: "le-havre",
    name: "Le Havre AC",
    shortName: "HAC",
    division: "Division 3",
    league: "Ligue 1",
    country: "France",
    logo: "https://crests.football-data.org/538.svg",
    primaryColor: "#002F6C",
    secondaryColor: "#87CEEB",
  },
  {
    id: "aj-auxerre",
    name: "AJ Auxerre",
    shortName: "AJA",
    division: "Division 3",
    league: "Ligue 1",
    country: "France",
    logo: "https://crests.football-data.org/519.svg",
    primaryColor: "#0055A5",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "angers-sco",
    name: "Angers SCO",
    shortName: "SCO",
    division: "Division 3",
    league: "Ligue 1",
    country: "France",
    logo: "https://crests.football-data.org/532.svg",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "as-saint-etienne",
    name: "AS Saint-Étienne",
    shortName: "ASSE",
    division: "Division 3",
    league: "Ligue 1",
    country: "France",
    logo: "https://crests.football-data.org/527.svg",
    primaryColor: "#008559",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "fc-metz",
    name: "FC Metz",
    shortName: "FCM",
    division: "Division 3",
    league: "Ligue 1",
    country: "France",
    logo: "https://crests.football-data.org/545.svg",
    primaryColor: "#67001E",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "fc-lorient",
    name: "FC Lorient",
    shortName: "FCL",
    division: "Division 3",
    league: "Ligue 1",
    country: "France",
    logo: "https://crests.football-data.org/525.svg",
    primaryColor: "#F37021",
    secondaryColor: "#000000",
  },
];

export const ALL_REAL_TEAMS: RealFootballTeam[] = [
  ...PREMIER_LEAGUE_TEAMS,
  ...LA_LIGA_TEAMS,
  ...LIGUE_1_TEAMS,
];

/**
 * Returns available real football teams for a player's division.
 */
export function getTeamsForDivision(division: string): RealFootballTeam[] {
  if (division === "Division 1") {
    return PREMIER_LEAGUE_TEAMS;
  }
  if (division === "Division 2") {
    return LA_LIGA_TEAMS;
  }
  if (division === "Division 3") {
    return LIGUE_1_TEAMS;
  }
  return ALL_REAL_TEAMS;
}

/**
 * Find team by ID or name
 */
export function findTeam(idOrName?: string | null): RealFootballTeam | undefined {
  if (!idOrName) return undefined;
  const normalized = idOrName.trim().toLowerCase();
  return ALL_REAL_TEAMS.find(
    (t) =>
      t.id.toLowerCase() === normalized ||
      t.name.toLowerCase() === normalized ||
      t.shortName.toLowerCase() === normalized
  );
}

/**
 * Resolves avatar or team crest for a player
 */
export function resolvePlayerAvatar(player?: {
  avatar?: string | null;
  realTeam?: string | null;
  gamerTag?: string;
}): string {
  if (player?.avatar && player.avatar.startsWith("http")) {
    return player.avatar;
  }
  if (player?.realTeam) {
    const team = findTeam(player.realTeam);
    if (team) return team.logo;
  }
  // Default fallback avatar placeholder or initial
  return `https://api.dicebear.com/7.x/bottts/svg?seed=${encodeURIComponent(player?.gamerTag || "Player")}`;
}
