export interface RealFootballTeam {
  id: string;
  name: string;
  shortName: string;
  short?: string;
  division: "Division 1" | "Division 2" | "Division 3";
  league: "Premier League" | "La Liga" | "Serie A" | "Ligue 1" | "Serie B";
  country: string;
  logo: string;
  primaryColor: string;
  secondaryColor: string;
}

// 20 Premier League Teams for Division 1
export const PREMIER_LEAGUE_TEAMS: RealFootballTeam[] = [
  {
    id: "arsenal",
    name: "Arsenal FC",
    shortName: "ARS",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/57.svg",
    primaryColor: "#EF0107",
    secondaryColor: "#063672",
  },
  {
    id: "aston-villa",
    name: "Aston Villa FC",
    shortName: "AVL",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/58.svg",
    primaryColor: "#95BFE5",
    secondaryColor: "#670E36",
  },
  {
    id: "bournemouth",
    name: "AFC Bournemouth",
    shortName: "BOU",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/1044.svg",
    primaryColor: "#DA291C",
    secondaryColor: "#000000",
  },
  {
    id: "brentford",
    name: "Brentford FC",
    shortName: "BRE",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/402.svg",
    primaryColor: "#E30613",
    secondaryColor: "#FBB800",
  },
  {
    id: "brighton",
    name: "Brighton & Hove Albion",
    shortName: "BHA",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/397.svg",
    primaryColor: "#0057B8",
    secondaryColor: "#FFCD00",
  },
  {
    id: "chelsea",
    name: "Chelsea FC",
    shortName: "CHE",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/61.svg",
    primaryColor: "#034694",
    secondaryColor: "#EE242C",
  },
  {
    id: "crystal-palace",
    name: "Crystal Palace FC",
    shortName: "CRY",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/354.svg",
    primaryColor: "#1B458F",
    secondaryColor: "#C4122E",
  },
  {
    id: "everton",
    name: "Everton FC",
    shortName: "EVE",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/62.svg",
    primaryColor: "#003399",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "fulham",
    name: "Fulham FC",
    shortName: "FUL",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/63.svg",
    primaryColor: "#000000",
    secondaryColor: "#CC0000",
  },
  {
    id: "ipswich-town",
    name: "Ipswich Town FC",
    shortName: "IPS",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/349.svg",
    primaryColor: "#0047AB",
    secondaryColor: "#ED1C24",
  },
  {
    id: "leicester-city",
    name: "Leicester City FC",
    shortName: "LEI",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/338.svg",
    primaryColor: "#003090",
    secondaryColor: "#FDBE11",
  },
  {
    id: "liverpool",
    name: "Liverpool FC",
    shortName: "LIV",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/64.svg",
    primaryColor: "#C8102E",
    secondaryColor: "#00B2A9",
  },
  {
    id: "manchester-city",
    name: "Manchester City",
    shortName: "MCI",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/65.svg",
    primaryColor: "#6CABDD",
    secondaryColor: "#1C2C5B",
  },
  {
    id: "manchester-united",
    name: "Manchester United",
    shortName: "MUN",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/66.svg",
    primaryColor: "#DA291C",
    secondaryColor: "#FBE122",
  },
  {
    id: "newcastle-united",
    name: "Newcastle United",
    shortName: "NEW",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/67.svg",
    primaryColor: "#241F20",
    secondaryColor: "#41B6E6",
  },
  {
    id: "nottingham-forest",
    name: "Nottingham Forest",
    shortName: "NFO",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/351.svg",
    primaryColor: "#DD0000",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "southampton",
    name: "Southampton FC",
    shortName: "SOU",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/340.svg",
    primaryColor: "#D71920",
    secondaryColor: "#130F54",
  },
  {
    id: "tottenham-hotspur",
    name: "Tottenham Hotspur",
    shortName: "TOT",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/73.svg",
    primaryColor: "#132257",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "west-ham-united",
    name: "West Ham United",
    shortName: "WHU",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/563.svg",
    primaryColor: "#7A263A",
    secondaryColor: "#1BB1E7",
  },
  {
    id: "wolverhampton",
    name: "Wolverhampton Wanderers",
    shortName: "WOL",
    division: "Division 1",
    league: "Premier League",
    country: "England",
    logo: "https://crests.football-data.org/76.svg",
    primaryColor: "#FDB913",
    secondaryColor: "#231F20",
  },
];

// 20 La Liga Teams for Division 2
export const LA_LIGA_TEAMS: RealFootballTeam[] = [
  {
    id: "real-madrid",
    name: "Real Madrid CF",
    shortName: "RMA",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/86.svg",
    primaryColor: "#FEBE10",
    secondaryColor: "#00529F",
  },
  {
    id: "fc-barcelona",
    name: "FC Barcelona",
    shortName: "BAR",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/81.svg",
    primaryColor: "#004D98",
    secondaryColor: "#A50044",
  },
  {
    id: "atletico-madrid",
    name: "Atlético de Madrid",
    shortName: "ATM",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/78.svg",
    primaryColor: "#CB3524",
    secondaryColor: "#272E61",
  },
  {
    id: "athletic-bilbao",
    name: "Athletic Club Bilbao",
    shortName: "ATH",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/77.svg",
    primaryColor: "#EE2524",
    secondaryColor: "#000000",
  },
  {
    id: "girona",
    name: "Girona FC",
    shortName: "GIR",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/298.svg",
    primaryColor: "#CD1318",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "real-sociedad",
    name: "Real Sociedad",
    shortName: "RSO",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/92.svg",
    primaryColor: "#0067B1",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "real-betis",
    name: "Real Betis",
    shortName: "BET",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/90.svg",
    primaryColor: "#0BB364",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "villarreal",
    name: "Villarreal CF",
    shortName: "VIL",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/94.svg",
    primaryColor: "#FFE667",
    secondaryColor: "#005187",
  },
  {
    id: "valencia",
    name: "Valencia CF",
    shortName: "VAL",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/95.svg",
    primaryColor: "#FF7300",
    secondaryColor: "#000000",
  },
  {
    id: "sevilla",
    name: "Sevilla FC",
    shortName: "SEV",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/559.svg",
    primaryColor: "#D4001F",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "osasuna",
    name: "CA Osasuna",
    shortName: "OSA",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/79.svg",
    primaryColor: "#D91A21",
    secondaryColor: "#001E62",
  },
  {
    id: "getafe",
    name: "Getafe CF",
    shortName: "GET",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/82.svg",
    primaryColor: "#005999",
    secondaryColor: "#D00C27",
  },
  {
    id: "celta-vigo",
    name: "RC Celta de Vigo",
    shortName: "CEL",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/558.svg",
    primaryColor: "#87CEEB",
    secondaryColor: "#C4122E",
  },
  {
    id: "mallorca",
    name: "RCD Mallorca",
    shortName: "MLL",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/89.svg",
    primaryColor: "#E20613",
    secondaryColor: "#000000",
  },
  {
    id: "las-palmas",
    name: "UD Las Palmas",
    shortName: "LPA",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/275.svg",
    primaryColor: "#FFD700",
    secondaryColor: "#005BAC",
  },
  {
    id: "rayo-vallecano",
    name: "Rayo Vallecano",
    shortName: "RAY",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/87.svg",
    primaryColor: "#E30613",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "espanyol",
    name: "RCD Espanyol",
    shortName: "ESP",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/80.svg",
    primaryColor: "#007FC8",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "leganes",
    name: "CD Leganés",
    shortName: "LEG",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/745.svg",
    primaryColor: "#0055A5",
    secondaryColor: "#009540",
  },
  {
    id: "real-valladolid",
    name: "Real Valladolid",
    shortName: "VLD",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/250.svg",
    primaryColor: "#5B2C6F",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "deportivo-alaves",
    name: "Deportivo Alavés",
    shortName: "ALA",
    division: "Division 2",
    league: "La Liga",
    country: "Spain",
    logo: "https://crests.football-data.org/263.svg",
    primaryColor: "#005CA9",
    secondaryColor: "#FFFFFF",
  },
];

// 20 Serie A Teams for Division 3
export const SERIE_A_TEAMS: RealFootballTeam[] = [
  {
    id: "inter",
    name: "Inter Milan",
    shortName: "INT",
    division: "Division 3",
    league: "Serie A",
    country: "Italy",
    logo: "https://crests.football-data.org/108.svg",
    primaryColor: "#010E80",
    secondaryColor: "#000000",
  },
  {
    id: "ac-milan",
    name: "AC Milan",
    shortName: "MIL",
    division: "Division 3",
    league: "Serie A",
    country: "Italy",
    logo: "https://crests.football-data.org/98.svg",
    primaryColor: "#FB090B",
    secondaryColor: "#000000",
  },
  {
    id: "juventus",
    name: "Juventus",
    shortName: "JUV",
    division: "Division 3",
    league: "Serie A",
    country: "Italy",
    logo: "https://crests.football-data.org/109.svg",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "atalanta",
    name: "Atalanta BC",
    shortName: "ATA",
    division: "Division 3",
    league: "Serie A",
    country: "Italy",
    logo: "https://crests.football-data.org/102.svg",
    primaryColor: "#1E71B8",
    secondaryColor: "#000000",
  },
  {
    id: "as-roma",
    name: "AS Roma",
    shortName: "ROM",
    division: "Division 3",
    league: "Serie A",
    country: "Italy",
    logo: "https://crests.football-data.org/100.png",
    primaryColor: "#8E1F2F",
    secondaryColor: "#F0BC42",
  },
  {
    id: "lazio",
    name: "SS Lazio",
    shortName: "LAZ",
    division: "Division 3",
    league: "Serie A",
    country: "Italy",
    logo: "https://crests.football-data.org/110.svg",
    primaryColor: "#87D8F7",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "napoli",
    name: "SSC Napoli",
    shortName: "NAP",
    division: "Division 3",
    league: "Serie A",
    country: "Italy",
    logo: "https://crests.football-data.org/113.png",
    primaryColor: "#003B64",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "fiorentina",
    name: "ACF Fiorentina",
    shortName: "FIO",
    division: "Division 3",
    league: "Serie A",
    country: "Italy",
    logo: "https://crests.football-data.org/99.svg",
    primaryColor: "#4F148B",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "bologna",
    name: "Bologna FC 1909",
    shortName: "BOL",
    division: "Division 3",
    league: "Serie A",
    country: "Italy",
    logo: "https://crests.football-data.org/103.svg",
    primaryColor: "#1A2F51",
    secondaryColor: "#A31621",
  },
  {
    id: "torino",
    name: "Torino FC",
    shortName: "TOR",
    division: "Division 3",
    league: "Serie A",
    country: "Italy",
    logo: "https://crests.football-data.org/586.svg",
    primaryColor: "#8A1E2D",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "monza",
    name: "AC Monza",
    shortName: "MON",
    division: "Division 3",
    league: "Serie A",
    country: "Italy",
    logo: "https://crests.football-data.org/5911.png",
    primaryColor: "#E30613",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "genoa",
    name: "Genoa CFC",
    shortName: "GEN",
    division: "Division 3",
    league: "Serie A",
    country: "Italy",
    logo: "https://crests.football-data.org/107.svg",
    primaryColor: "#990000",
    secondaryColor: "#002B49",
  },
  {
    id: "lecce",
    name: "US Lecce",
    shortName: "LEC",
    division: "Division 3",
    league: "Serie A",
    country: "Italy",
    logo: "https://crests.football-data.org/850.png",
    primaryColor: "#FFED00",
    secondaryColor: "#DA291C",
  },
  {
    id: "verona",
    name: "Hellas Verona FC",
    shortName: "VER",
    division: "Division 3",
    league: "Serie A",
    country: "Italy",
    logo: "https://crests.football-data.org/450.svg",
    primaryColor: "#002B49",
    secondaryColor: "#FFCC00",
  },
  {
    id: "udinese",
    name: "Udinese Calcio",
    shortName: "UDI",
    division: "Division 3",
    league: "Serie A",
    country: "Italy",
    logo: "https://crests.football-data.org/115.svg",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "cagliari",
    name: "Cagliari Calcio",
    shortName: "CAG",
    division: "Division 3",
    league: "Serie A",
    country: "Italy",
    logo: "https://crests.football-data.org/104.svg",
    primaryColor: "#A6192E",
    secondaryColor: "#00205B",
  },
  {
    id: "empoli",
    name: "Empoli FC",
    shortName: "EMP",
    division: "Division 3",
    league: "Serie A",
    country: "Italy",
    logo: "https://crests.football-data.org/445.png",
    primaryColor: "#005BAA",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "parma",
    name: "Parma Calcio 1913",
    shortName: "PAR",
    division: "Division 3",
    league: "Serie A",
    country: "Italy",
    logo: "https://crests.football-data.org/112.svg",
    primaryColor: "#FFE500",
    secondaryColor: "#002B7F",
  },
  {
    id: "como",
    name: "Como 1907",
    shortName: "COM",
    division: "Division 3",
    league: "Serie A",
    country: "Italy",
    logo: "https://crests.football-data.org/1072.svg",
    primaryColor: "#0047AB",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "venezia",
    name: "Venezia FC",
    shortName: "VEN",
    division: "Division 3",
    league: "Serie A",
    country: "Italy",
    logo: "https://crests.football-data.org/454.svg",
    primaryColor: "#FF6600",
    secondaryColor: "#006633",
  },
];

// 20 Serie B Teams for Division 3 (Available when Division 3 competitors exceed 20)
export const SERIE_B_TEAMS: RealFootballTeam[] = [
  {
    id: "sassuolo",
    name: "US Sassuolo Calcio",
    shortName: "SAS",
    division: "Division 3",
    league: "Serie B",
    country: "Italy",
    logo: "https://crests.football-data.org/471.svg",
    primaryColor: "#00A850",
    secondaryColor: "#000000",
  },
  {
    id: "salernitana",
    name: "US Salernitana 1919",
    shortName: "SAL",
    division: "Division 3",
    league: "Serie B",
    country: "Italy",
    logo: "https://crests.football-data.org/455.svg",
    primaryColor: "#8A151B",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "frosinone",
    name: "Frosinone Calcio",
    shortName: "FRO",
    division: "Division 3",
    league: "Serie B",
    country: "Italy",
    logo: "https://crests.football-data.org/470.svg",
    primaryColor: "#FFD700",
    secondaryColor: "#0055A5",
  },
  {
    id: "palermo",
    name: "Palermo FC",
    shortName: "PAL",
    division: "Division 3",
    league: "Serie B",
    country: "Italy",
    logo: "https://crests.football-data.org/114.png",
    primaryColor: "#F8A3BC",
    secondaryColor: "#000000",
  },
  {
    id: "sampdoria",
    name: "UC Sampdoria",
    shortName: "SAM",
    division: "Division 3",
    league: "Serie B",
    country: "Italy",
    logo: "https://crests.football-data.org/584.svg",
    primaryColor: "#003D7C",
    secondaryColor: "#E30613",
  },
  {
    id: "spezia",
    name: "Spezia Calcio",
    shortName: "SPE",
    division: "Division 3",
    league: "Serie B",
    country: "Italy",
    logo: "https://crests.football-data.org/488.svg",
    primaryColor: "#FFFFFF",
    secondaryColor: "#000000",
  },
  {
    id: "cremonese",
    name: "US Cremonese",
    shortName: "CRE",
    division: "Division 3",
    league: "Serie B",
    country: "Italy",
    logo: "https://crests.football-data.org/466.svg",
    primaryColor: "#8B1C1D",
    secondaryColor: "#9E9E9E",
  },
  {
    id: "pisa",
    name: "Pisa Sporting Club",
    shortName: "PIS",
    division: "Division 3",
    league: "Serie B",
    country: "Italy",
    logo: "https://crests.football-data.org/588.svg",
    primaryColor: "#003DA5",
    secondaryColor: "#000000",
  },
  {
    id: "brescia",
    name: "Brescia Calcio",
    shortName: "BSC",
    division: "Division 3",
    league: "Serie B",
    country: "Italy",
    logo: "https://crests.football-data.org/449.svg",
    primaryColor: "#003366",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "bari",
    name: "SSC Bari",
    shortName: "BRI",
    division: "Division 3",
    league: "Serie B",
    country: "Italy",
    logo: "https://crests.football-data.org/453.png",
    primaryColor: "#E30613",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "cesena",
    name: "Cesena FC",
    shortName: "CES",
    division: "Division 3",
    league: "Serie B",
    country: "Italy",
    logo: "https://crests.football-data.org/1109.png",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "modena",
    name: "Modena FC 2018",
    shortName: "MOD",
    division: "Division 3",
    league: "Serie B",
    country: "Italy",
    logo: "https://crests.football-data.org/460.png",
    primaryColor: "#FFD700",
    secondaryColor: "#003399",
  },
  {
    id: "reggiana",
    name: "AC Reggiana 1919",
    shortName: "REG",
    division: "Division 3",
    league: "Serie B",
    country: "Italy",
    logo: "https://crests.football-data.org/1137.svg",
    primaryColor: "#7B1113",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "juve-stabia",
    name: "SS Juve Stabia",
    shortName: "JST",
    division: "Division 3",
    league: "Serie B",
    country: "Italy",
    logo: "https://crests.football-data.org/1138.svg",
    primaryColor: "#FFD700",
    secondaryColor: "#002060",
  },
  {
    id: "carrarese",
    name: "Carrarese Calcio 1908",
    shortName: "CAR",
    division: "Division 3",
    league: "Serie B",
    country: "Italy",
    logo: "https://crests.football-data.org/1132.svg",
    primaryColor: "#FFD700",
    secondaryColor: "#003399",
  },
  {
    id: "cosenza",
    name: "Cosenza Calcio",
    shortName: "COS",
    division: "Division 3",
    league: "Serie B",
    country: "Italy",
    logo: "https://crests.football-data.org/1152.png",
    primaryColor: "#C8102E",
    secondaryColor: "#002F6C",
  },
  {
    id: "cittadella",
    name: "AS Cittadella",
    shortName: "CIT",
    division: "Division 3",
    league: "Serie B",
    country: "Italy",
    logo: "https://crests.football-data.org/585.svg",
    primaryColor: "#800000",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "mantova",
    name: "Mantova 1911",
    shortName: "MAN",
    division: "Division 3",
    league: "Serie B",
    country: "Italy",
    logo: "https://upload.wikimedia.org/wikipedia/commons/e/eb/Logo_Mantova_1911.svg",
    primaryColor: "#CC0000",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "catanzaro",
    name: "US Catanzaro 1929",
    shortName: "CAT",
    division: "Division 3",
    league: "Serie B",
    country: "Italy",
    logo: "https://upload.wikimedia.org/wikipedia/it/c/c5/Stemma_US_Catanzaro_1929.svg",
    primaryColor: "#FFD700",
    secondaryColor: "#CC0000",
  },
  {
    id: "sudtirol",
    name: "FC Südtirol",
    shortName: "SUD",
    division: "Division 3",
    league: "Serie B",
    country: "Italy",
    logo: "https://upload.wikimedia.org/wikipedia/commons/1/14/Logo_prime_stagioni_fc_sudtirol.png",
    primaryColor: "#FFFFFF",
    secondaryColor: "#CC0000",
  },
];

// Alias for backwards compatibility
export const LIGUE_1_TEAMS = SERIE_A_TEAMS;

export const ALL_REAL_TEAMS: RealFootballTeam[] = [
  ...PREMIER_LEAGUE_TEAMS,
  ...LA_LIGA_TEAMS,
  ...SERIE_A_TEAMS,
  ...SERIE_B_TEAMS,
];

/**
 * Returns available real football teams for a player's division.
 * For Division 3, Serie B teams become available when competitor count exceeds 20.
 * NB: Division 3 only - Division 1 and 2 exclusively feature Premier League and La Liga.
 */
export function getTeamsForDivision(
  division: string,
  includeSerieBOrCount?: boolean | number
): RealFootballTeam[] {
  if (division === "Division 1") {
    return PREMIER_LEAGUE_TEAMS;
  }
  if (division === "Division 2") {
    return LA_LIGA_TEAMS;
  }
  if (division === "Division 3") {
    const shouldIncludeSerieB =
      typeof includeSerieBOrCount === "number"
        ? includeSerieBOrCount > 20
        : Boolean(includeSerieBOrCount);

    return shouldIncludeSerieB
      ? [...SERIE_A_TEAMS, ...SERIE_B_TEAMS]
      : SERIE_A_TEAMS;
  }
  return ALL_REAL_TEAMS;
}

/**
 * Find team by ID or name
 */
export function findTeam(idOrName?: string | null): RealFootballTeam | undefined {
  if (!idOrName) return undefined;
  const normalized = idOrName.trim().toLowerCase();
  return ALL_REAL_TEAMS.find(
    (t) =>
      t.id.toLowerCase() === normalized ||
      t.name.toLowerCase() === normalized ||
      t.shortName.toLowerCase() === normalized
  );
}

/**
 * Resolves avatar or team crest for a player
 */
export function resolvePlayerAvatar(player?: {
  avatar?: string | null;
  realTeam?: string | null;
  gamerTag?: string;
}): string {
  if (player?.avatar && player.avatar.startsWith("http")) {
    return player.avatar;
  }
  if (player?.realTeam) {
    const team = findTeam(player.realTeam);
    if (team) return team.logo;
  }
  // Default fallback avatar placeholder or initial
  return `https://api.dicebear.com/7.x/bottts/svg?seed=${encodeURIComponent(player?.gamerTag || "Player")}`;
}
